### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by dupillir** [kfuku52/csubst#29]
Hello,

I am currently using the CSUBST tool which works great!
However when trying out the test run with the simulated data for the first time I encountered the following problem :

`AttributeError: module 'numpy' has no attribute 'int'`

Following the informations from this [link](https://github.com/WongKinYiu/yolov7/issues/1280) I understand that the latest version of numpy (1.24.2) does not support the initial `np.int` attribute anymore and replaced it with `.int`.
 
Thus the instructions from the CSUBST code are incompatible with the latest version of numpy which will automatically be downloaded if you install it as of now.

To bypass this problem I downgraded to a previous version of numpy  using the following command which allowed CSUBST to run.

`pip install "numpy<1.24.0"`

**Comment by kfuku52** [comment]
Thank you for reporting the problem. I will fix it soon to make CSUBST compatible with the latest numpy.

**Comment by kfuku52** [comment]
The latest version (v1.3.1) should now be compatible with numpy 1.24. With v1.3.1, `csubst analyze` and `csubst simulate` worked well without the error in my test dataset. Please reinstall CSUBST with `pip install git+https://github.com/kfuku52/csubst` and try again when you need numpy >=1.24. I will close this issue, but please feel free to reopen it if the problem persists.
