### ISSUE TITLE
Error during instantaneous rate matrix generation

### ISSUE THREAD

**Issue by agneeshbarua** [kfuku52/csubst#38]
Dear Fukushima-sensei,

Thank you so much for writing the CSUBST program and providing such detailed documentation as a part of the paper. I have been trying to run CSUBST on my own data and have encountered an issue. 

I initially tested the program on an orthogroup dataset with one gene per species. It worked fine and produced the output. But when I tried it with larger orthogroups (multiple paralogs per species), I am getting the attached error. There seems to be some error with the state matrix during the Instantaneous substitution rate matrix generation step. It's strange because the matrix does get produced, but the program crashes right afterwards. 

I have attached the slurm error file, the conda environment list, and slurm script (test with single array) I'm using.

Hoping you can provide some advice. 

Thank you.

[array_csubst.txt](https://github.com/kfuku52/csubst/files/11286580/array_csubst.txt)
[conda_env.txt](https://github.com/kfuku52/csubst/files/11286581/conda_env.txt)
[error_slurm_out.txt](https://github.com/kfuku52/csubst/files/11286591/error_slurm_out.txt)

**Comment by agneeshbarua** [comment]
Dear sensei, 

I went back and performed the analysis in a new fresh directory and still got the same error. I've attached the alignment, gene trees, and foreground file. I didn't include the intermediary iqtree files as they get generated pretty quickly. 

[foreground.txt](https://github.com/kfuku52/csubst/files/11308208/foreground.txt)
[OG0002198_cds_hammer.txt](https://github.com/kfuku52/csubst/files/11308209/OG0002198_cds_hammer.txt)
[OG0002198_generax.txt](https://github.com/kfuku52/csubst/files/11308211/OG0002198_generax.txt)

**Comment by kfuku52** [comment]
Internal node and tip labels should be uniquely assigned, but your tree seems to have non-unique internal node names. `species_22` appeared three times and potentially other names too. The error should be gone if you could run CSUBST again with unique names or after deleting all internal node names if they are not necessary. NWKIT drop may be useful to remove the labels.
https://github.com/kfuku52/nwkit/wiki/nwkit-drop

**Comment by agneeshbarua** [comment]
Thank you for pointing out the error. It works perfectly now!

**Comment by kfuku52** [comment]
I'm glad to hear that it worked :)
