### ISSUE TITLE
Questions for calculating convergent gene

### ISSUE THREAD

**Issue by HHH101** [kfuku52/csubst#43]
Hi,
Thanks for your tools, your application is very interesting!
I have several qestions:
1. Does the "csubst analyze" command is like the branch site model in PAML?
2. Here, I filtered out convergent gene step by step, and I don't know if it is correct:
(1) I got the "cutoff_stat" in the "csubst_cb_stats.tsv" file (e.g. in your example is OCNany2spe=2.0 omegaCany2spe=5.0)
(2) If the "csubst_cb_2.tsv" file have data which OCNany2spe>2.0 & omegaCany2spe>5.0, indicates this gene is a convergent gene? Do we need to look at branch_id to make sure the branch is a foreground branch?

Many thanks for your help!
I am looking forward for your replying!

**Comment by kfuku52** [comment]
>Does the "csubst analyze" command is like the branch site model in PAML?

It's more close to the branch model. omega_C is calculated for branch combinations over all sites.

>If the "csubst_cb_2.tsv" file have data which OCNany2spe>2.0 & omegaCany2spe>5.0, indicates this gene is a convergent gene? Do we need to look at branch_id to make sure the branch is a foreground branch?

It depends on how you specified foreground. `is_fg` should be `Y` if you correctly specify the branch in `--foreground`.

**Comment by HHH101** [comment]
I got it, many thanks!
You mean a convergent gene of the foreground species should be OCNany2spe>2.0 & omegaCany2spe>5.0 & is_fg=Y

**Comment by kfuku52** [comment]
The threshould `OCNany2spe>2.0 & omegaCany2spe>5.0` may be changed depending on your purpose, but yes, that's correct.

**Comment by HHH101** [comment]
Another question is your application seems can handle gene duplicates, can I use all the orthogroups (rather than single copy) to run the model?

**Comment by kfuku52** [comment]
Yes, there is no limitation regarding gene duplications and losses, at least in running CSUBST.
