### ISSUE TITLE
Malformed selection error in csubst_site

### ISSUE THREAD

**Issue by agneeshbarua** [kfuku52/csubst#49]
Dear Kenji,

I am trying to use csubst_site to map convergent substitutions on protein structures. Most of them came out fine except for one sample where I am getting the above error. In the pdf that gets generated, none of the convergent sites are plotted. I have used my own determined protein models from SwissModel as the pdb input. The alignment of the model and input sequence looks good as well. 

Another quick question, the input or the site algorithm is the same as for the csubst analysis algorithm correct? In my case, it's the output of cdskit hammer. 

I've attached the log file of the site algorithm.

Thanks
[csubst.34202113_6.txt](https://github.com/kfuku52/csubst/files/12907098/csubst.34202113_6.txt)

**Comment by kfuku52** [comment]
>Another quick question, the input or the site algorithm is the same as for the csubst analysis algorithm correct? In my case, it's the output of cdskit hammer.

Yes, the inputs should be the same between `site` and `analyze`.

Could you provide a reproducible example including input files and CSUBST command?

**Comment by agneeshbarua** [comment]
Dear Kenji,

Here's a folder with all the data to reproduce the above. 
[Issue.zip](https://github.com/kfuku52/csubst/files/12909409/Issue.zip)

**Comment by agneeshbarua** [comment]
Dear Kenji,

Here are the files to reproduce the above analysis.

[Issue.zip](https://github.com/kfuku52/csubst/files/12909412/Issue.zip)

**Comment by kfuku52** [comment]
The error appears to stem from a lack of convergence and/or double divergence in specified branches (I tested with `23,26,51,55,116,130,175,180,218`). Following this comment, I will release version 1.3.17, which should allow for the creation of a .pse file without encountering any errors. However, the results may lack biological significance due to the absence of convergence.
