### ISSUE TITLE
ValueError:Quantiles

### ISSUE THREAD

**Issue by agneeshbarua** [kfuku52/csubst#52]
Dear Kenji, 

I am running CSUSBT and have encountered the following error:

File "<__array_function__ internals>", line 200, in quantile
  File "/users/abarua/myproject_envs/Pigmentation_env/lib/python3.11/site-packages/numpy/lib/function_base.py", line 4460, in quantile
    raise ValueError("Quantiles must be in the range [0, 1]")
    
 I've attached a folder containing all the data that gave me this error. 
[value_test.zip](https://github.com/kfuku52/csubst/files/13424200/value_test.zip)

**Comment by kfuku52** [comment]
Thank you for reporting! Could you share the CSUBST command you used?

**Comment by kfuku52** [comment]
I got different error. Is it the tree you used as a CSUBST input?

```
ValueError: Internal node labels are not unique. Please provide unique internal node labels or delete them from --rooted_tree_file. For the label deletion, nwkit drop may be useful: https://github.com/kfuku52/nwkit/wiki/nwkit-drop
```

**Comment by agneeshbarua** [comment]
Here is the command:

#Run CSUBST
csubst analyze --alignment_file ../$name"_cds_hammer.fa" \
               --rooted_tree_file ../$name"_generax.nwk" \
               --threads 4 \
               --cutoff_stat 'OCNany2spe,3.0|omegaCany2spe,5.0' \
               --max_arity 10
               
$name = Orthogroup name (OG)


Not sure why you got the node label error, the files have the same sets of genes.

**Comment by kfuku52** [comment]
OK, I will delete internal node names.

**Comment by kfuku52** [comment]
The bug should be fixed now. Please feel free to reopen the issue if the problem persists.
