### ISSUE TITLE
How to identify convergent sites by csubst?

### ISSUE THREAD

**Issue by xinghua1001** [kfuku52/csubst#58]
Hi,

Thank you for proposing the very smart new metric OmegaC and developing csubst. I'm not sure whether I understand it correctly, OmegaC is calculated by gene. After running csubst, we can know which gene is selected by filter the OmegaC. I'm particularly interested in the highly repetitive adaptive convergence. However, the question is that can we identify which amino acid site is the convergent sites underlying the phenotype by csubst, because I could not find this in the csubst results.

Thanks!

XL

**Comment by kfuku52** [comment]
Thank you for using CSUBST. For the identification of convergent sites, please refer to this page: https://github.com/kfuku52/csubst/wiki/Mapping-convergent-substitutions-on-protein-structures

**Comment by xinghua1001** [comment]
Hi Dr. Fukushima,

Is it possible that although OmegaC is significant, csubst site can not detect convergent sites. In my understanding, OmegaC is calculated at the gene level. Even if protein evolution rate is converged, the amino acids may not be the same among foreground lineages.

Thanks,
Xinghua

**Comment by kfuku52** [comment]
It is difficult to imagine a scenario where no convergent site is detected, if both `omegaC_any2spe` and `OCN_any2spe` are meaningfully high. I can assist you better if you could share your results.
