### ISSUE TITLE
Species or gene tree?

### ISSUE THREAD

**Issue by bmm514** [kfuku52/csubst#59]
Hi,

I am going to be using CSUBST in an exploratory manner on a number of genes from a phylogeny and I have both a species tree and gene trees (for each gene) available to me. Can you recommend the use of one over the other or will it not make too much difference?

Many thanks,
Ben

**Comment by kfuku52** [comment]
Thank you for considering the use of CSUBST. In this regard, please refer to this page: https://github.com/kfuku52/csubst/wiki/FAQ

**Comment by bmm514** [comment]
Thank you for the quick response, I don't know how I missed this before! Just a quick clarification, CSUBST will still be able to detect convergent evolution for orthogroups with lineage-specific duplications in them? If so is there any limit to the number of lineage-specific duplications that can be present for a species?

**Comment by kfuku52** [comment]
CSUBST does not have a hard limit on the number of duplications in the tree, but analyzing extremely large trees with thousands of genes may be challenging.
