### ISSUE TITLE
Why Does csubst analyze Generate Output Files Even When Cutoff Criteria Aren't Met?

### ISSUE THREAD

**Issue by zhangxinyu328** [kfuku52/csubst#63]
Hi,
   I used the following command to run csubst analyze: `--fg_exclude_wg no --fg_stem_only no --cutoff_stat 'OCNany2spe,5.0|omegaCany2spe,2.0' --max_arity 13 --exhaustive_until 1
`
This produced the output files csubst_cb_2.tsv through csubst_cb_6.tsv. However, none of the records in csubst_cb_2.tsv meet the specified cutoff (OCNany2spe > 5.0 and omegaCany2spe > 2.0). Could you help clarify why the analysis proceeded without meeting these criteria? Additionally, is the output in csubst_cb_3-6.tsv still reliable given this discrepancy?

Thank you!

**Comment by kfuku52** [comment]
Thank you for reporting. Could you share the output files to assess if there is any potential problem?

**Comment by zhangxinyu328** [comment]
Of course.
[output.zip](https://github.com/user-attachments/files/17587888/output.zip)

**Comment by kfuku52** [comment]
That does seem unusual. Could you please provide additional details, including the standard output from the CSUBST run and a set of input files you used?

**Comment by zhangxinyu328** [comment]
Thank you for your response. The folder KCNJ11 contains my input files, while the folder work092 holds the output files generated by running the code `csubst analyze --alignment_file KCNJ11.fasta --rooted_tree_file KCNJ11.tree --foreground foreground_low.txt --fg_exclude_wg no --fg_stem_only no --cutoff_stat 'OCNany2spe,5.0|omegaCany2spe,2.0' --max_arity 13 --exhaustive_until 1 ` with parallel. I noticed that some output files were saved in KCNJ11, and I’m not sure if this might affect the results.

[data.zip](https://github.com/user-attachments/files/17607303/data.zip)

**Comment by kfuku52** [comment]
Thank you. Could you provide `foreground_low.txt` as well?

**Comment by zhangxinyu328** [comment]
Sorry, I missed it when uploading.
[foreground_low.txt](https://github.com/user-attachments/files/17674549/foreground_low.txt)

**Comment by kfuku52** [comment]
>However, none of the records in csubst_cb_2.tsv meet the specified cutoff (OCNany2spe > 5.0 and omegaCany2spe > 2.0).

I identified nine branch combinations that meet the criteria of OCNany2spe > 5.0 and omegaCany2spe > 2.0 at K = 2. I suspect that the parameter `--cutoff_stat 'OCNany2spe,5.0|omegaCany2spe,2.0'` may have been incorrectly specified. Should it instead use the thresholds from the NEE paper: `--cutoff_stat 'OCNany2spe,2.0|omegaCany2spe,5.0'`?

branch_id_1 | branch_id_2 | is_fg | is_mf | is_mg | omegaCany2spe | OCNany2spe
-- | -- | -- | -- | -- | -- | --
26 | 130 | Y | N | N | 4.6593 | 52.0484
26 | 170 | Y | N | N | 2.0747 | 129.7035
26 | 298 | Y | N | N | 2.0525 | 128.732
26 | 379 | Y | N | N | 2.0975 | 19.5039
26 | 473 | Y | N | N | 3.0933 | 78.148
130 | 170 | Y | N | N | 2.3793 | 55.0494
130 | 298 | Y | N | N | 2.2891 | 55.2836
170 | 473 | Y | N | N | 2.5273 | 91.9996
298 | 473 | Y | N | N | 2.505 | 92.9867
